//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dock
    {
        public string id { get; set; }
        public string title { get; set; }
        public string name { get; set; }
        public string enabled { get; set; }
        public Nullable<int> position { get; set; }
        public string url { get; set; }
        public string app_url { get; set; }
        public string projectid { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
