//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public string id { get; set; }
        public string status { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string purpose { get; set; }
        public string bookmark_url { get; set; }
        public string url { get; set; }
        public string app_url { get; set; }
        public string bookmarked { get; set; }
        public string todosetid { get; set; }
        public string todoseturl { get; set; }
    }
}
